on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-18.04
    # if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
      name: ðŸšš Get latest code

    - name: Build
      uses: TartanLlama/actions-eleventy@v1.1

    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        local-dir: ./dist
        ftp-server: sftp://sftp.op-de-kop.nl/public/sites/www.op-de-kop.nl
        ftp-username: 198511
        ftp-password: ${{ secrets.deploy_password }}
        git-ftp-args: --insecure
