on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ secrets.deploy_username }}
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp-1a.mijndomein-ws.nl/public/sites/www.op-de-kop.nl
        ftp-username: 198511
        ftp-password: ${{ secrets.deploy_password }}
        git-ftp-args: --insecure
