on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'

    steps:
    - run: npm install
    - name: installing package.json dependencies
      uses: mikeal/npx@master

    - run: npm run build
    - name: ğŸ”¨ building 11ty site..
      uses: mikeal/npx@master

    - run: echo ${{ secrets.deploy_username }}
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        local-dir: ./dist
        ftp-server: sftp://sftp.op-de-kop.nl/public/sites/www.op-de-kop.nl
        ftp-username: 198511
        ftp-password: ${{ secrets.deploy_password }}
        git-ftp-args: --insecure
