on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ secrets.deploy_username }}
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2

    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp.op-de-kop.nl
        ftp-username: 198511
        ftp-port: 22
        ftp-password: ${{ secrets.deploy_password }}
        git-ftp-args: --insecure
